# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
connection: &connection
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  
  timeout: 5000
  min_messages: warning

development:
  <<: *connection
  database: groupfire_dev
test: &test
  <<: *connection
  database: groupfire_test

production:
  <<: *connection
  database: groupfire_dev

cucumber:
  <<: *test